<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" total="5" passed="4">
  <reporter-output>
  </reporter-output>
  <suite name="Suite" duration-ms="157464" started-at="2016-03-03T03:25:50Z" finished-at="2016-03-03T03:28:27Z">
    <groups>
    </groups>
    <test name="Test" duration-ms="157464" started-at="2016-03-03T03:25:50Z" finished-at="2016-03-03T03:28:27Z">
      <class name="UserRegistrationTest">
        <test-method status="PASS" signature="accessToSite()[pri:1, instance:UserRegistrationTest@566776ad]" name="accessToSite" duration-ms="8841" started-at="2016-03-02T22:25:50Z" finished-at="2016-03-02T22:25:59Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- accessToSite -->
        <test-method status="PASS" signature="registration()[pri:2, instance:UserRegistrationTest@566776ad]" name="registration" duration-ms="112157" started-at="2016-03-02T22:25:59Z" finished-at="2016-03-02T22:27:51Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- registration -->
      </class> <!-- UserRegistrationTest -->
      <class name="RegistarionLogInTest">
        <test-method status="PASS" signature="LogIn()[pri:1, instance:RegistarionLogInTest@6bf256fa]" name="LogIn" duration-ms="18339" started-at="2016-03-02T22:27:51Z" finished-at="2016-03-02T22:28:09Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- LogIn -->
        <test-method status="PASS" signature="clickOnUserName()[pri:2, instance:RegistarionLogInTest@6bf256fa]" name="clickOnUserName" duration-ms="8372" started-at="2016-03-02T22:28:09Z" finished-at="2016-03-02T22:28:18Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- clickOnUserName -->
        <test-method status="FAIL" signature="clickOnMyFav()[pri:3, instance:RegistarionLogInTest@6bf256fa]" name="clickOnMyFav" duration-ms="9729" started-at="2016-03-02T22:28:18Z" finished-at="2016-03-02T22:28:27Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [Jezoo26] but found [Pete]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [Jezoo26] but found [Pete]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertEqualsImpl(Assert.java:135)
	at org.testng.Assert.assertEquals(Assert.java:116)
	at org.testng.Assert.assertEquals(Assert.java:190)
	at org.testng.Assert.assertEquals(Assert.java:200)
	at com.user.reg.UserRegistration.clickOnMyFav(UserRegistration.java:39)
	at RegistarionLogInTest.clickOnMyFav(RegistarionLogInTest.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:293)
	at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:84)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:91)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:200)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:153)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:103)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- clickOnMyFav -->
      </class> <!-- RegistarionLogInTest -->
    </test> <!-- Test -->
  </suite> <!-- Suite -->
</testng-results>
